### PR TITLE
org-node: move unix socket to tmp directory

### PR DESCRIPTION
**Pull request by Ryanmtate**

### CODE REVIEW

**Review by FintanH — COMMENTED** [review]
It might be more future-proof to use [temp_dir](https://doc.rust-lang.org/std/env/fn.temp_dir.html) instead of hard-coding the string.

Alternatively, we could use [TempDir](https://docs.rs/tempdir/0.3.7/tempdir/struct.TempDir.html) to create a named temporary directory.

**Review by cloudhead — APPROVED** [review]

**Comment by Ryanmtate** [comment]
> It might be more future-proof to use [temp_dir](https://doc.rust-lang.org/std/env/fn.temp_dir.html) instead of hard-coding the string.
> 
> Alternatively, we could use [TempDir](https://docs.rs/tempdir/0.3.7/tempdir/struct.TempDir.html) to create a named temporary directory.

Good call, ffc2e59 uses `temp_dir` over the hard coding. `TempDir` looks great too! Not opposed to adding another dependency.

**Comment by cloudhead** [comment]
Merged in cdb32c2

**Comment by FintanH** [comment]
> Good call, ffc2e59 uses temp_dir over the hard coding. TempDir looks great too! Not opposed to adding another dependency.

Up to you peeps :) Seems like the previous code is merged now :sweat_smile:

**Pull request closed without merging**
